In [1]:
import pandas as pd
df=pd.read_csv("used_cars.csv")

In [2]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         4009 non-null   object
 1   model         4009 non-null   object
 2   model_year    4009 non-null   int64
 3   milage        4009 non-null   object
 4   fuel_type     3839 non-null   object
 5   engine        4009 non-null   object
 6   transmission  4009 non-null   object
 7   ext_col       4009 non-null   object
 8   int_col       4009 non-null   object
 9   accident      3896 non-null   object
 10  clean_title   3413 non-null   object
 11  price         4009 non-null   object
dtypes: int64(1), object(11)
memory usage: 376.0+ KB

In [5]:
df.shape

(4009, 12)

In [6]:
df.describe()

        model_year
count  4009.000000
mean   2015.515590
std       6.104816
min    1974.000000
25%    2012.000000
50%    2017.000000
75%    2020.000000
max    2024.000000

In [7]:
df.sample(5)

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
2135,BMW,M3 Base,2008,"94,000 mi.",Gasoline,414.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,6-Speed M/T,Gray,Red,None reported,Yes,"$25,999"
2562,Audi,A3 2.0T Premium,2018,"36,500 mi.",Gasoline,220.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,Gray,Silver,At least 1 accident or damage reported,Yes,"$25,500"
1888,Tesla,Model S 100D,2018,"33,500 mi.",NaN,518.0HP Electric Motor Electric Fuel System,A/T,Gray,Black,None reported,Yes,"$51,900"
472,Rivian,R1S Adventure Package,2023,"2,500 mi.",NaN,835.0HP Electric Motor Electric Fuel System,A/T,Gray,Gray,None reported,Yes,"$91,000"
2998,RAM,1500 Laramie,2022,"16,616 mi.",Gasoline,5.7L V8 16V MPFI OHV,8-Speed Automatic,Diamond Black,Black,None reported,NaN,"$45,999"

In [8]:
df.isnull().sum()

brand             0
model             0
model_year        0
milage            0
fuel_type       170
engine            0
transmission      0
ext_col           0
int_col           0
accident        113
clean_title     596
price             0
dtype: int64

In [10]:
df[df.duplicated()]

Empty DataFrame
Columns: [brand, model, model_year, milage, fuel_type, engine, transmission, ext_col, int_col, accident, clean_title, price]
Index: []

In [13]:
for col in ["brand","model","model_year","ext_col","int_col"]:
    print(col)
    print(df[col].unique())
    print(df[col].value_counts())

brand
['Ford' 'Hyundai' 'Lexus' 'INFINITI' 'Audi' 'Acura' 'BMW' 'Tesla' 'Land'
 'Aston' 'Toyota' 'Lincoln' 'Jaguar' 'Mercedes-Benz' 'Dodge' 'Nissan'
 'Genesis' 'Chevrolet' 'Kia' 'Jeep' 'Bentley' 'Honda' 'Lucid' 'MINI'
 'Porsche' 'Hummer' 'Chrysler' 'Volvo' 'Cadillac' 'Lamborghini' 'Maserati'
 'Volkswagen' 'Subaru' 'Rivian' 'GMC' 'RAM' 'Alfa' 'Ferrari' 'Scion'
 'Mitsubishi' 'Mazda' 'Saturn' 'Bugatti' 'Polestar' 'Rolls-Royce'
 'McLaren' 'Buick' 'Lotus' 'Pontiac' 'FIAT' 'Karma' 'Saab' 'Mercury'
 'Plymouth' 'smart' 'Maybach' 'Suzuki']
brand
Ford             386
BMW              375
Mercedes-Benz    315
Chevrolet        292
Porsche          201
Audi             200
Toyota           199
Lexus            163
Jeep             143
Land             130
Nissan           116
Cadillac         107
GMC               91
RAM               91
Dodge             90
Tesla             87
Kia               76
Hyundai           72
Subaru            64
Acura             64
Mazda             64
Honda             63
INFINITI          59
Volkswagen        59
Lincoln           52
Jaguar            47
Volvo             38
Maserati          34
Bentley           33
MINI              33
Buick             30
Chrysler          28
Lamborghini       26
Genesis           20
Mitsubishi        20
Alfa              19
Rivian            17
Hummer            16
Pontiac           15
Ferrari           12
Rolls-Royce       11
Aston              9
Scion              6
McLaren            6
Saturn             5
FIAT               5
Lotus              4
Lucid              3
Mercury            3
Karma              2
Saab               2
Bugatti            1
Polestar           1
Plymouth           1
smart              1
Maybach            1
Suzuki             1
Name: count, dtype: int64
model
['Utility Police Interceptor Base' 'Palisade SEL' 'RX 350 RX 350' ...
 'Martin DB7 Vantage Volante' 'Impala 2LZ' 'Taycan']
model
M3 Base             30
F-150 XLT           24
Corvette Base       22
1500 Laramie        18
Camaro 2SS          17
                    ..
Mazda6 Signature     1
SLK-Class SLK320     1
Protege DX           1
Q5 40 Premium        1
Passat 2.5 SE        1
Name: count, Length: 1898, dtype: int64
model_year
[2013 2021 2022 2015 2016 2017 2001 2020 2019 2003 2018 2023 2000 2006
 2011 2012 2007 2014 2005 2009 2010 2004 2008 1997 1999 1993 2002 1998
 2024 1996 1974 1992 1995 1994]
model_year
2022    354
2021    350
2020    322
2018    315
2019    297
2016    268
2017    259
2015    228
2023    226
2014    181
2013    158
2012    141
2011    124
2008    113
2010    100
2007     98
2005     72
2009     72
2006     66
2004     60
2003     49
2001     34
2002     32
2000     17
1999     15
1998     11
1993      9
1997      9
1996      8
1994      7
2024      6
1995      6
1992      1
1974      1
Name: count, dtype: int64
ext_col
['Black' 'Moonlight Cloud' 'Blue' 'Glacier White Metallic' 'Silver'
 'Green' 'Fuji White' 'Yellow' 'White' 'Gray' 'Purple'
 'Iconic Silver Metallic' 'Mythos Black Metallic' 'Red' 'Gold'
 'Lunar Silver Metallic' 'Mountain Air Metallic' 'Caspian Blue'
 'Tango Red Metallic' '–' 'Alpine White' 'BLU ELEOS' 'Horizon Blue'
 'Granite Crystal Clearcoat Metallic' 'Orange' 'Beige' 'Rift Metallic'
 'Atomic Silver' 'Summit White' 'Imperial Blue Metallic'
 'Magnetic Gray Clearcoat' 'Bright White Clearcoat' 'Typhoon Gray'
 'Crystal Black Silica' 'Arctic Gray Metallic' 'Selenite Grey Metallic'
 'Ultra Black' 'Lunare White Metallic' 'Hyper Red'
 'Daytona Gray Pearl Effect' 'Vik Black' 'Pacific Blue Metallic'
 'Obsidian Black Metallic' 'Silver Ice Metallic' 'Sonic Silver Metallic'
 'Nightfall Mica' 'Apex Blue' 'Go Mango!' 'Ingot Silver Metallic'
 'Midnight Black Metallic' 'Black Clearcoat' 'Thunder Gray'
 'Bianco Monocerus' 'Verde' 'Wind Chill Pearl' 'Mythos Black'
 'Patriot Blue Pearlcoat' 'Black Cherry' 'Yulong White'
 'Donington Grey Metallic' 'Ruby Red Metallic Tinted Clearcoat'
 'Platinum Quartz Metallic' 'Matador Red Metallic' 'Blu'
 'Mosaic Black Metallic' 'Jungle Green' 'BLACK' 'Deep Crystal Blue Mica'
 'Beluga Black' 'Eiger Grey' 'Ebony Black' 'Brown' 'Indus Silver'
 'Ibis White' 'Bianco Icarus Metallic' 'Infrared Tintcoat'
 'Midnight Black' 'Phytonic Blue Metallic' 'Quartz White'
 'Rapid Red Metallic Tinted Clearcoat' 'Cobra Beige Metallic' 'Pure White'
 'Snow White Pearl' 'DB Black Clearcoat' 'Firenze Red Metallic'
 'Anodized Blue Metallic' 'MANUFAKTUR Diamond White Bright'
 'Santorin Black' 'Glacier' 'Delmonico Red Pearlcoat' 'Brilliant Black'
 'Magnetite Black Metallic' 'Carpathian Grey Premium Metallic'
 'Majestic Black Pearl' 'Northsky Blue Metallic' 'Baltic Gray'
 'Machine Gray Metallic' 'Twilight Black' 'Pearl White' 'Diamond Black'
 'Maroon' 'Firecracker Red Clearcoat' 'Oxford White' 'Glacier White'
 'Flame Red Clearcoat' 'White Clearcoat' 'Ice' 'Silver Zynith'
 'Silky Silver' 'Ametrin Metallic' 'Deep Black Pearl Effect'
 'Shimmering Silver' 'Gecko Pearlcoat' 'Onyx' 'Rosso Mars Metallic'
 'Shoreline Blue Pearl' 'Santorini Black'
 'White Platinum Tri-Coat Metallic' 'Sparkling Silver' 'Chalk' 'BLUE'
 'Dazzling White' 'Santorini Black Metallic' 'Selenite Gray Metallic'
 'Metallic' 'Ebony Twilight Metallic' 'Polymetal Gray Metallic'
 'Oryx White Prl' 'Black Forest Green' 'Gun Metallic' 'Jet Black Mica'
 'Dark Gray Metallic' 'Firenze Red' 'Glacial White Pearl'
 'designo Diamond White Metallic' 'Blue Metallic'
 'Isle of Man Green Metallic' 'Black Noir Pearl' 'Volcano Grey Metallic'
 'Soul Red Crystal Metallic' 'Dark Moss' 'Passion Red'
 'Typhoon Gray Metallic' 'Onyx Black' 'Redline Red'
 'Navarra Blue Metallic' 'Brands Hatch Gray Metallic'
 'Daytona Gray Pearl Effect w/ Black Roof' 'Hampton Gray' 'Ultra White'
 'Hydro Blue Pearlcoat' 'Sandstone Metallic' 'Portofino Blue Metallic'
 'Sangria Red' 'Magnetic Metallic' 'Tan' 'Platinum White Pearl'
 'designo Diamond White' 'Anthracite Blue Metallic' 'Velvet Red Pearlcoat'
 'Silver Mist' 'Antimatter Blue Metallic' 'Cirrus Silver Metallic' 'Pink'
 'Cayenne Red Tintcoat' 'Garnet Red Metallic' 'Black Obsidian'
 'Pristine White' 'Nebula Gray Pearl' 'Super White'
 'Gentian Blue Metallic' 'Midnight Blue Metallic' 'Yulong' 'Rosso Corsa'
 'Matte White' 'Navarra Blue' 'Silver Radiance' 'Iridium Metallic'
 'Magnetic Black' 'Chronos Gray Metallic' 'Pacific Blue'
 'Eiger Grey Metallic' 'White Diamond Tri-Coat' 'Stormy Sea'
 'Dark Matter Metallic' 'Billet Clearcoat Metallic'
 'Brilliant Silver Metallic' 'Liquid Platinum' 'Vulcano Black Metallic'
 'Diamond White' 'White Frost Tri-Coat' 'Aventurine Green Metallic'
 'Tempest' 'Alfa White' 'Star White' 'Titanium Silver' 'Caviar'
 'Kodiak Brown Metallic' 'Majestic Plum Metallic' 'Navarre Blue'
 'Bronze Dune Metallic' 'Radiant Red Metallic II'
 'Dark Moon Blue Metallic' 'Manhattan Noir Metallic'
 'Agate Black Metallic' 'Frozen White' 'Bianco Isis'
 'Phantom Black Pearl Effect / Black Roof' 'Kemora Gray Metallic'
 'Shadow Black' 'Graphite Grey Metallic' 'Emerald Green Metallic'
 'Orca Black Metallic' 'Chronos Gray' 'Daytona Gray'
 'Billet Silver Metallic Clearcoat' 'Sting Gray Clearcoat'
 'Maximum Steel Metallic' 'Carbonized Gray Metallic' 'Ruby Flare Pearl'
 'Crimson Red Tintcoat' 'Blueprint' 'Balloon White'
 'Snowflake White Pearl' 'Crystal White Pearl' 'Quicksilver Metallic'
 'Dark Sapphire' 'Carbon Black Metallic' 'Sunset Drift Chromaflair'
 'Shadow Gray Metallic' 'Granite' 'Frozen Dark Silver Metallic'
 'Black Sapphire Metallic' 'Quartz Blue Pearl' 'Iridescent Pearl Tricoat'
 'Satin Steel Metallic' 'Aurora Black' 'Black Raven' 'Florett Silver'
 'Cajun Red Tintcoat' 'Nero Daytona' 'Red Multi' 'Dark Ash Metallic'
 'Rich Garnet Metallic' 'Nero Noctis' 'Scarlet Ember' 'Blue Reflex Mica'
 'Snowflake White Pearl Metallic' 'Grigio Nimbus'
 'Granite Crystal Metallic Clearcoat' 'Stellar Black Metallic'
 'Dark Slate Metallic' 'Vega Blue' 'Stone Gray Metallic'
 'Matador Red Mica' 'Barcelona Red' 'Bayside Blue' 'Tungsten Metallic'
 'Mineral White' 'Siren Red Tintcoat' 'Octane Red Pearlcoat' 'Wolf Gray'
 'Fountain Blue' 'Obsidian' 'Volcanic Orange' 'Dark Graphite Metallic'
 'Designo Magno Matte' 'Phantom Black' 'Crystal Black'
 'Red Quartz Tintcoat' 'Carrara White Metallic' 'Blue Caelum'
 'designo Diamond White Bright' 'Iridium Silver Metallic'
 'Mango Tango Pearlcoat' 'GT SILVER' 'Crystal Black Pearl'
 'Eminent White Pearl' 'Lunar Blue Metallic' 'Magnetic Gray Metallic'
 'Arctic White' 'Silver Flare Metallic' 'Emin White' 'Custom Color'
 'Ember Pearlcoat' 'Twilight Blue Metallic' 'Burnished Bronze Metallic'
 'Ice Silver Metallic' 'Magnetite Gray Metallic' 'Jupiter Red'
 'Midnight Silver Metallic' 'Hellayella Clearcoat' 'Ironman Silver'
 'Alta White' 'Python Green' 'China Blue' 'Portofino Gray'
 'White Knuckle Clearcoat' 'Nautical Blue Pearl' 'Silician Yellow'
 'Arancio Borealis' 'Rosso' 'Graphite Grey' 'Lizard Green' 'Super Black'
 'Kinetic Blue' 'Electric Blue Metallic' 'Glacier Blue Metallic'
 'Red Obsession' 'Platinum Gray Metallic' 'Remington Red Metallic'
 'Reflex Silver' 'Deep Blue Metallic' 'Glacier Silver Metallic'
 'Carpathian Grey' 'Nightfall Gray Metallic' 'Lunar Rock'
 'Quartzite Grey Metallic' 'C / C']
ext_col
Black                     905
White                     816
Gray                      496
Silver                    374
Blue                      349
                         ...
Glacier Blue Metallic       1
Electric Blue Metallic      1
Kinetic Blue                1
Super Black                 1
Deep Crystal Blue Mica      1
Name: count, Length: 319, dtype: int64
int_col
['Black' 'Gray' 'Ebony.' 'Green' 'Pimento / Ebony' 'Brown' 'White' '–'
 'Beige' 'Jet Black' 'Light Gray' 'Anthracite' 'Red' 'Nero Ade' 'Blue'
 'Charcoal' 'Rioja Red' 'Canberra Beige/Black' 'Roast' 'Ivory / Ebony'
 'Silk Beige/Black' 'Medium Pewter' 'Ice' 'Black / Express Red'
 'Obsidian Black' 'Ebony' 'Orange' 'Caramel' 'Orchid' 'Graphite'
 'Tan/Ebony' 'Cappuccino' 'Nero' 'Sahara Tan' 'BLACK' 'Hotspur' 'Blk'
 'Black Onyx' 'Nougat Brown' 'Titan Black' 'Oyster W/Contrast' 'Silver'
 'Macchiato Beige/Black' 'Sand Beige' 'Navy Pier' 'WHITE' 'Parchment.'
 'Sarder Brown' 'Grace White' 'Cloud' 'Espresso' 'Mesa' 'Whisper Beige'
 'Medium Dark Slate' 'Gold' 'Camel Leather' 'Tupelo' 'Black/Red'
 'Parchment' 'Beluga Hide' 'Charles Blue' 'Global Black'
 'Titan Black / Quarzit' 'Mocha' 'Portland' 'Medium Light Camel'
 'Black / Saddle' 'Ash' 'Ebony / Pimento' 'Tan' 'Mistral Gray / Raven'
 'Graystone' 'Satin Black' 'Sandstone' 'Medium Stone' 'ORANGE'
 'Pimento Red w/Ebony' 'Macchiato' 'Ebony Black' 'Pearl Beige'
 'Sakhir Orange' 'Kyalami Orange' 'Almond Beige' 'Medium Earth Gray'
 'Diesel Gray / Black' 'Boulder' 'Walnut' 'Charcoal Black' 'Dark Auburn'
 'Tan/Ebony/Ebony' 'Amber' 'Silk Beige/Espresso Brown' 'Black / Brown'
 'Sakhir Orange/Black' 'Black / Stone Grey' 'AMG Black' 'Slate' 'BEIGE'
 'Canberra Beige' 'Magma Red' 'Saiga Beige' 'Saddle Brown'
 'Light Titanium' 'Dark Gray' 'Platinum' 'Ebony/Light Oyster Stitch'
 'Shale' 'Red/Black' 'Agave Green' 'Cobalt Blue' 'Deep Cypress' 'Ceramic'
 'Camel' 'Rhapsody Blue' 'Light Platinum / Jet Black' 'Shara Beige'
 'Dark Galvanized' 'Giallo Taurus / Nero Ade' 'Yellow'
 'Black w/Red Stitching' 'Black/Saddle Brown' 'Light Slate'
 'Black/Gun Metal' 'White / Brown' 'Brandy' 'Mountain Brown' 'Linen'
 'Porpoise' 'Aragon Brown' 'Oyster/Black' 'Gideon' 'Chestnut'
 'Red / Black' 'Bianco Polar' 'Deep Garnet' 'Dark Ash'
 'Ebony / Ebony Accents' 'Rock Gray' 'Cocoa / Dune' 'Beluga'
 'Carbon Black' 'Sport' 'Medium Ash Gray' 'Black/Graphite'
 'Macchiato/Magmagrey' 'Classic Red' 'Chateau' 'Graphite w/Gun Metal'
 'Tension' 'Adrenaline Red' 'Hotspur Hide' 'Gray w/Blue Bolsters'
 'Very Light Cashmere' 'Black / Gray' 'Deep Chestnut' 'Black / Graphite']
int_col
Black                   2025
Beige                    538
Gray                     472
Brown                    157
–                        133
                        ...
Gray w/Blue Bolsters       1
Very Light Cashmere        1
Black / Gray               1
Deep Chestnut              1
Black / Graphite           1
Name: count, Length: 156, dtype: int64

In [14]:
df.describe(include="all")

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
count,4009,4009,4009.000000,4009,3839,4009,4009,4009,4009,3896,3413,4009
unique,57,1898,NaN,2818,7,1146,62,319,156,2,1,1569
top,Ford,M3 Base,NaN,"110,000 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,A/T,Black,Black,None reported,Yes,"$15,000"
freq,386,30,NaN,16,3309,52,1037,905,2025,2910,3413,39
mean,NaN,NaN,2015.515590,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,6.104816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,1974.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,2012.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,2017.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,2020.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,2024.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Data Cleaning

In [15]:
# Currently the price include dollar symbol and comma like this $10,300 which we have to filter

df["price"]=(df["price"].str.replace("$","",regex=False)
            .str.replace(",","",regex=False)
            .astype(int))

df["price"]

0        10300
1        38005
2        54598
3        15500
4        34999
         ...
4004    349950
4005     53900
4006     90998
4007     62999
4008     40000
Name: price, Length: 4009, dtype: int64

In [19]:
# Handle Milage same as price (Milage is in this form 51,000 mi.)

df["milage"]=(df["milage"].str.replace("mi.","",regex=False)
             .str.replace(",","",regex=False)
             .astype(int))
df["milage"].describe()

count      4009.000000
mean      64717.551010
std       52296.599459
min         100.000000
25%       23044.000000
50%       52775.000000
75%       94100.000000
max      405000.000000
Name: milage, dtype: float64

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         4009 non-null   object
 1   model         4009 non-null   object
 2   model_year    4009 non-null   int64
 3   milage        4009 non-null   int64
 4   fuel_type     3839 non-null   object
 5   engine        4009 non-null   object
 6   transmission  4009 non-null   object
 7   ext_col       4009 non-null   object
 8   int_col       4009 non-null   object
 9   accident      3896 non-null   object
 10  clean_title   3413 non-null   object
 11  price         4009 non-null   int64
dtypes: int64(3), object(9)
memory usage: 376.0+ KB

##### Handling Missing Values #######

In [21]:
df.isnull().sum()

brand             0
model             0
model_year        0
milage            0
fuel_type       170
engine            0
transmission      0
ext_col           0
int_col           0
accident        113
clean_title     596
price             0
dtype: int64

In [26]:
# Handling missing values of "fuel_type"
# Since fuel type is of type object we will use mode to impute

df["fuel_type"]=df["fuel_type"].fillna(df["fuel_type"].mode()[0])
df["fuel_type"].unique()

array(['E85 Flex Fuel', 'Gasoline', 'Hybrid', 'Diesel', 'Plug-In Hybrid',
       '–', 'not supported'], dtype=object)

In [29]:
#Handling "accident" feature and "clean_title" feature

df["accident"]=df["accident"].fillna("Unknown")
df["clean_title"]=df["clean_title"].fillna("Unknown")

In [33]:
print(df["accident"].unique())
print(df["clean_title"].unique())

['At least 1 accident or damage reported' 'None reported' 'Unknown']
['Yes' 'Unknown']

In [34]:

#Check for duplicate rows
df.duplicated().sum()

np.int64(0)

## Feature Engineering

In [35]:
# Instead of "model_year" we can create feature car age

curr_yr=2026
df["car_age"]=curr_yr-df["model_year"]

df.drop("model_year", axis=1, inplace=True)

df["car_age"].describe()

count    4009.000000
mean       10.484410
std         6.104816
min         2.000000
25%         6.000000
50%         9.000000
75%        14.000000
max        52.000000
Name: car_age, dtype: float64

In [36]:
df["accident"].unique()

array(['At least 1 accident or damage reported', 'None reported',
       'Unknown'], dtype=object)

In [39]:
# Now we will change these values [None reported,At least 1 accident,Unknown] into [No Accident,Accident,Unknown]


# Create a dictionary mapping the old names to the new names
accident_mapping={
    "None reported": "No Accident",
    "At least 1 accident or damage reported": "Accident",
    "Unknown": "Unknown"
}

# Replace old value to new
df["accident"]=df["accident"].replace(accident_mapping)

In [40]:
df["accident"].unique()

array(['Accident', 'No Accident', 'Unknown'], dtype=object)

In [43]:

# Clean the title, convert ["Yes","Unknown"] to [0,1]

df["clean_title"]=(df["clean_title"].replace("Yes",1).replace("Unknown",0).astype(int))

In [47]:
df["clean_title"].dtype

dtype('int64')

#### Creating new feature "is premium" for premium brand cars

In [51]:
#Check all the brands name
df["brand"].value_counts()

brand
Ford             386
BMW              375
Mercedes-Benz    315
Chevrolet        292
Porsche          201
Audi             200
Toyota           199
Lexus            163
Jeep             143
Land             130
Nissan           116
Cadillac         107
GMC               91
RAM               91
Dodge             90
Tesla             87
Kia               76
Hyundai           72
Subaru            64
Acura             64
Mazda             64
Honda             63
INFINITI          59
Volkswagen        59
Lincoln           52
Jaguar            47
Volvo             38
Maserati          34
Bentley           33
MINI              33
Buick             30
Chrysler          28
Lamborghini       26
Genesis           20
Mitsubishi        20
Alfa              19
Rivian            17
Hummer            16
Pontiac           15
Ferrari           12
Rolls-Royce       11
Aston              9
Scion              6
McLaren            6
Saturn             5
FIAT               5
Lotus              4
Lucid              3
Mercury            3
Karma              2
Saab               2
Bugatti            1
Polestar           1
Plymouth           1
smart              1
Maybach            1
Suzuki             1
Name: count, dtype: int64

In [52]:
# 1. Define the set of luxury and exotic brands
luxury_brands = {
    "BMW", "Mercedes-Benz", "Porsche", "Audi", "Lexus", "Land", 
    "Cadillac", "Tesla", "Acura", "INFINITI", "Lincoln", "Jaguar", 
    "Volvo", "Maserati", "Bentley", "Lamborghini", "Genesis", "Alfa", 
    "Rivian", "Ferrari", "Rolls-Royce", "Aston", "McLaren", "Lotus", 
    "Lucid", "Karma", "Saab", "Bugatti", "Polestar", "Maybach"
}

# 2. Create the binary column (1 for luxury, 0 for mainstream)
df["is_luxury"]=df["brand"].isin(luxury_brands).astype(int)

df["is_luxury"].value_counts()

is_luxury
1    2039
0    1970
Name: count, dtype: int64

#### Create feature engine size from engine

In [58]:
# Every engine include engine size, so we can extract them and create new feature

# Extract engine size (in liters)
df["engine_size"] = df["engine"].str.extract(r'(\d+\.?\d*)\s*(?:L|Liter)', expand=False)

# Convert to float
df["engine_size"] = df["engine_size"].astype(float)

df[["engine", "engine_size"]].head()

                                              engine  engine_size
0  300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...          3.7
1                               3.8L V6 24V GDI DOHC          3.8
2                                     3.5 Liter DOHC          3.5
3  354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...          3.5
4                         2.0L I4 16V GDI DOHC Turbo          2.0

In [59]:
df[["engine", "engine_size"]]

                                                 engine  engine_size
0     300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...          3.7
1                                  3.8L V6 24V GDI DOHC          3.8
2                                        3.5 Liter DOHC          3.5
3     354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...          3.5
4                            2.0L I4 16V GDI DOHC Turbo          2.0
...                                                 ...          ...
4004                   6.0L W12 48V PDI DOHC Twin Turbo          6.0
4005      349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel          3.0
4006                                           Electric          NaN
4007      450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel          3.5
4008       248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel          2.0

[4009 rows x 2 columns]

In [63]:
df[df["engine_size"].isna()][["engine", "fuel_type"]].head(20)

                                          engine fuel_type
9    534.0HP Electric Motor Electric Fuel System  Gasoline
10                                            V6  Gasoline
32                                        120 AH    Hybrid
44   536.0HP Electric Motor Electric Fuel System  Gasoline
68   536.0HP Electric Motor Electric Fuel System  Gasoline
92   835.0HP Electric Motor Electric Fuel System  Gasoline
120                                           V6  Gasoline
122  835.0HP Electric Motor Electric Fuel System  Gasoline
129  620.0HP Electric Motor Electric Fuel System  Gasoline
130                                            –         –
155  455.0HP Electric Motor Electric Fuel System  Gasoline
189  455.0HP Electric Motor Electric Fuel System  Gasoline
225  670.0HP Electric Motor Electric Fuel System  Gasoline
236                                     Electric  Gasoline
253  355.0HP Electric Motor Electric Fuel System  Gasoline
257                                            –         –
266  329.0HP Electric Motor Electric Fuel System  Gasoline
298  271.0HP Electric Motor Electric Fuel System  Gasoline
321                                     Electric  Gasoline
338                                            –         –